# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "sosi-ea-plugin"
  tags:
  - "private"
spec:
  type: "service"
  lifecycle: "production"
  owner: "standardisering"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "sosi-ea-plugin"
  links:
  - url: "https://github.com/kartverket/sosi-ea-plugin"
    title: "sosi-ea-plugin på GitHub"
spec:
  type: "repo"
  owner: "standardisering"
  dependencyOf:
  - "component:sosi-ea-plugin"
